CREATE DATABASE IF NOT EXISTS REMOTERC;
USE REMOTERC;

-- @Table
CREATE TABLE PRODUTOS (
	CProd INT AUTO_INCREMENT, 
    Descricao VARCHAR(255), 
    Peso CHAR(2) DEFAULT 'KG' NOT NULL,
	ValorUnit DECIMAL(7.2) NOT NULL,
PRIMARY KEY (CProd));

CREATE TABLE VENDEDOR (
	CVend INT AUTO_INCREMENT,
	Nome VARCHAR(20) NOT NULL, 
    Salario  DECIMAL(7.2) NOT NULL, 
    FSalario INT NOT NULL,
PRIMARY KEY (CVend));

CREATE TABLE CLIENTE (
	CCli INT AUTO_INCREMENT, 
    Nome VARCHAR(20) NOT NULL, 
    Endereco VARCHAR(100) NOT NULL, 
    Cidade VARCHAR(25) NOT NULL, 
    UF CHAR(2) DEFAULT 'SP' NOT NULL,
PRIMARY KEY (CCli));

-- @Insert 
INSERT INTO PRODUTOS VALUES (1, "Teclado", 'KG', 35.00);
INSERT INTO PRODUTOS VALUES (2, "Mouse,", 'KG', 25.00);
INSERT INTO PRODUTOS VALUES (3, "HD,", 'KG', 350.00);

INSERT INTO VENDEDOR VALUES (1, "Ronaldo", 3512.00, 1);
INSERT INTO VENDEDOR VALUES (2, "Robertson,", 3225.00, 2);
INSERT INTO VENDEDOR VALUES (3, "Clodoaldo,", 4350.00, 3);

INSERT INTO CLIENTE VALUES (11, "Bruno", "Rua 1 456", "Rio Claro", 'SP');
INSERT INTO CLIENTE VALUES (12, "Cláudio", "Rua Quadrada 234", "Campinas", 'SP');
INSERT INTO CLIENTE VALUES (13, "Cremilda", "Rua das Flores 666", "São Paulo", 'SP');

-- @Update
SET SQL_SAFE_UPDATES = 0;	# Desativa o modo de segurança para permitir atualizações | Evita: Error Code: 1175 
UPDATE VENDEDOR SET Salario = 3150.00 WHERE FSalario = 1;
UPDATE VENDEDOR SET Salario = Salario * 1.10 WHERE FSalario = 2;
UPDATE VENDEDOR SET Salario = 3500.00 WHERE FSalario = 3;

-- @Delete
DELETE FROM PRODUTOS;
DELETE FROM VENDEDOR;
DELETE FROM CLIENTE;
