CREATE DATABASE ATIVIDADE;
USE ATIVIDADE;

-- @Entity
CREATE TABLE IF NOT EXISTS Fornecedor (
	Fcodigo INT AUTO_INCREMENT, 
	Fnome VARCHAR(100) NOT NULL, 
    Status VARCHAR(15) DEFAULT "Ativo" NOT NULL, 
    Cidade VARCHAR(100),
PRIMARY KEY (Fcodigo));

CREATE TABLE IF NOT EXISTS Peca (
	Pcodigo INT AUTO_INCREMENT, 
    Pnome VARCHAR(100) NOT NULL, 
    -- Cor ,
    -- Peso , 
    -- Cidade ,
PRIMARY KEY (Pcodigo));

CREATE TABLE IF NOT EXISTS Instituicao (
	Icodigo INT AUTO_INCREMENT, 
    nome VARCHAR(100) NOT NULL,
PRIMARY KEY (Icodigo));

CREATE TABLE IF NOT EXISTS Projeto (
	PRcod INT AUTO_INCREMENT, 
    PRnome VARCHAR(100) NOT NULL, 
    -- Cidade , 
    -- Icod ,
    -- FOREIGN KEY () REFERENCES DEPARTAMENTO (),
PRIMARY KEY (PRcod));

CREATE TABLE IF NOT EXISTS Fornecimento (
	ID_fornecedor INT AUTO_INCREMENT,
	Fcod INT NOT NULL, 
    Pcod INT NOT NULL, 
    PRcod INT NOT NULL, 
    Quantidade INT NOT NULL,
	-- FOREIGN KEY () REFERENCES DEPARTAMENTO (),
	-- FOREIGN KEY () REFERENCES DEPARTAMENTO (),
	-- FOREIGN KEY () REFERENCES DEPARTAMENTO (),
PRIMARY KEY (ID_fornecedor));
